### ISSUE TITLE
🐛[BUG] MEGA 访问失败

### ISSUE THREAD

**Issue by fight-fly** [BeyondDimension/SteamTools#3356]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

弹窗

>  MEGA failed to load because 
> 
> The file "https://eu.static.mega.co.nz/4/js/mega-1_c50e3dcd069699707a529effaf74c51009f25d8bcd430a1b009705c1604335ac.js" is corrupt.
> 
> Please click OK to refresh and try again.
> 
> If the problem persists, please try disabling all third-party browser extensions, update your browser and MEGA browser extension to the latest version. If that does not help, contact support@mega.nz
> 
> BrowserID: mozilla/5.0 (windows nt 10.0; win64; x64; rv:109.0) gecko/20100101 firefox/116.0
> Static server: https://eu.static.mega.co.nz/4/
> Flipped to default static: no
> Date/time: 2024-06-02T03:41:50.963Z

无反应

### 📷 复现步骤

1.  打开分享地址
2.  得到弹窗信息
3.  等待无回应

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：win10
- 下载渠道：github
- 程序版本：3.0.0 rc8
- 是否包含独立运行时：

**Comment by fight-fly** [comment]
网络延迟，自动连发了两个issue
已关闭 https://github.com/BeyondDimension/SteamTools/issues/3355

**Comment by fight-fly** [comment]
零插件平时不适用的Edge一样
![sshot-1](https://github.com/BeyondDimension/SteamTools/assets/70288629/39ce4c4f-6cc4-4157-affb-ad5a3da98ccc)

**Comment by fight-fly** [comment]
![sshot-2](https://github.com/BeyondDimension/SteamTools/assets/70288629/601c71f7-41e0-44f1-88b9-69015bfe7cf5)

**Comment by living2room** [comment]
MEGA failed to load because 

The file "https://eu.static.mega.co.nz/4/lang/en_24745bc2a56c3e26dec15445d180bdc613a1f0d14dbf1bd7863daf33b8a8d9c4.json" is corrupt.

Please click OK to refresh and try again.

If the problem persists, please try disabling all third-party browser extensions, update your browser and MEGA browser extension to the latest version. If that does not help, contact support@mega.nz

BrowserID: mozilla/5.0 (windows nt 10.0; win64; x64; rv:127.0) gecko/20100101 firefox/127.0
Static server: https://eu.static.mega.co.nz/4/
Flipped to default static: no
Date/time: 2024-06-18T02:29:33.254Z

**Comment by wockkkk** [comment]
问题同上

**Comment by rmbadmin** [comment]
已热更新修复
