### ISSUE TITLE
🧐[Question] Using the Steam++ in Ubuntu 22.04 ，CheckRootCertificate, ErrCode: TrustRootCertificateFail

### ISSUE THREAD

**Issue by qq745639151** [BeyondDimension/SteamTools#3415]
![image](https://github.com/user-attachments/assets/ec82d192-24dc-4167-90a0-f33eeff43973)

**Comment by qq745639151** [comment]
I have tried to import the certificate . but it is not helpful.

**Comment by Mossimos** [comment]
To initialize certutil using the offline_init.sh script in the Scripts directory, execute the following command:
```
    certutil -d $HOME/.pki/nssdb -L
    ret=$?
    if [ $ret -ne 0 ]; then
        echo "即将初始化 certutil \$HOME/.pki/nssdb"
        mkdir -p $HOME/.pki
        mkdir -p $HOME/.pki/nssdb
        chmod 700 $HOME/.pki/nssdb
        certutil -d $HOME/.pki/nssdb -N --empty-password
    else
        echo "certutil nssdb 正常"
    fi
```
![QQ_1722035596263](https://github.com/user-attachments/assets/42e07b5e-f26c-4ddb-92d8-c2dc0de916d4)
certutil detected database corruption
```
 certutil -d $HOME/.pki/nssdb -L
```

**Comment by qq745639151** [comment]
@Mossimos Thank you for your reply. but it doesn't work. and I find a little mistake in offline_init.sh. the variable ```dotnet_path``` is not defined. I fix it but it also doesn't work.
![image](https://github.com/user-attachments/assets/142642f6-566b-4b65-a1c6-d32f33afb978)

**Comment by Mossimos** [comment]
From the picture, it appears that the nssdb has been properly initialized and the certificates have been correctly installed. However, the program is still displaying the previous error code. The offline installation script indeed missed one parameter, which I will fix later. If it still doesn't work, please check if the user running the program is the same as the user who ran the offline installation, since the $HOME parameter is used to locate the nssdb database.

**Comment by qq745639151** [comment]
I reinstalled the software with the default installation path, the problem did not occur.
I think it is due to I change the default installation path and my system language is chinese. When I use the default installation path, the problem is disappeared.
![image](https://github.com/user-attachments/assets/700d8acd-ec0f-4a8c-b6f7-37e3e840077a)

**Comment by qq745639151** [comment]
Thank you for your patience again.

**Comment by Mossimos** [comment]
The issue is not related to the default installation path. The program reports an error indicating that the $HOME/.pki/nssdb database is either corrupted or missing. Google Chrome uses this location by default to store and trust certificates, so the program also checks for certificates in this location.
After fixing the previous script, the program installed in other paths should also return to normal.

**Comment by qq745639151** [comment]
May I make a small request？  Please support Chinese， Because the installation script prompts an error: cannot access ```/home/fanlei/Desktop//Watt Toolkit.desktop ``` Because My Desktop path is ```/home/fanlei/桌面/```
![image](https://github.com/user-attachments/assets/8ab5eb37-7fa0-40bb-a929-d4a6ebf57e6b)

**Comment by Mossimos** [comment]
脚本是支持的  看起来是 target_dir 参数结尾多了一个 / 后续我测试好去修复下  离线安装脚本很久没更新了。 另外 Linux 下是自带了运行时的 在程序目录下 dotnet 文件夹中

**Comment by qq745639151** [comment]
OK，感谢，还是用中文交流方便，哈哈.
我的桌面目录没有Desktop，我那个桌面路径直接是中文的，所以它找不到。donet那个好像也是预设的路径变量不太对。

**Comment by Mossimos** [comment]
离线的预设确实不对 但是在线的脚本是对的 后续我也把这个优化下。
